name: memolink
description: App per salvare e organizzare link social in modo intelligente.
publish_to: "none"

version: 4.1.0+18

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.5
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  share_plus: ">=10.1.4 <12.0.0"
  file_picker: ^10.3.10
  lottie: ^3.1.0
  http: ^1.2.1
  reorderable_grid_view: ^2.2.8
  purchases_flutter: ^9.14.0
  purchases_ui_flutter: ^9.14.0
  package_info_plus: ^8.0.0
  font_awesome_flutter: ^10.7.0
  app_links: ^6.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/images/
    - assets/images/categories/
    - assets/images/iloveabitini/
    - assets/lottie/
    - assets/sounds/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"